# Site settings
title: Bytes of Knowledge
email: jb3689@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A web developer's thoughts on Ruby, Javascript, and other things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jbodah.github.io" # the base hostname & protocol for your site
github_username:  jbodah

# Build settings
markdown: redcarpet

permalink: /blog/:year/:month/:day/:title/
